project:
  type: website
  output-dir: docs

website:
  title: "Yajun Liu"
  favicon: dove-solid.svg
  navbar:
    title: false # override printing your website `title` (e.g. "Sam Csik" on line 6) in the top left corner of your navbar
    logo: dove-solid.svg
    logo-alt: "Alt text for logo"
    right:
      - href: index.qmd
        text: Home
      - education.qmd
      - work.qmd
      - publication.qmd
      - href: CV.pdf
        text: CV
        target: _blank # opens link (or page) in a new browser tab
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Yajun Liu
    center: "Address: 3 Charles Street, Edinburgh, EH8 9AD"
    

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    #css: styles.css
    toc: true
    page-layout: full
  

editor: visual

