project:
  type: website
  output-dir: docs

website:
  title: "Yajun Liu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - experience.qmd
      - tutoring.qmd
      - publication.qmd
      - href: CV.pdf
        text: CV
        target: _blank # opens link (or page) in a new browser tab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

