project:
  type: website
  output-dir: docs

website:
  title: "liuyajun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - experience.qmd
      - tutoring.qmd
      - publication.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

