---
title: "Publications & Presentations"
---

<h1>Publications</h1>

-   <h2>Accepted and Submitted</h2>

    -   <p>

        Liu, Y., Sorace, A., & Smith, K. (Accepted). Mandarin bilingual speakers undergoing attrition produce more explicit referring expressions. Bilingualism: Language and Cognition. <a href="final_manuscript.pdf" target="_blank">Check out here</a>

    -   Liu, Y., Sorace, A., & Smith, K. (2025). Beyond Crosslinguistic influence: Mandarin Speakers with Exposure to Null-subject Languages Nonetheless Use Fewer Null Pronouns in Mandarin. Proceedings of the 47th Annual Meeting of the Cognitive Science Society \[Oral presentation\], 878-884. <a href="https://escholarship.org/uc/item/4h69k203" target="_blank">Check out here</a>

    -   Liu, Y., Sorace, A., & Smith, K. (Preprint). Do bilinguals avoid ambiguity? An experimental study of lexical ambiguity in spoken Mandarin. <a href="do_bilinguals_avoid_ambiguity_YL+AS+KS.pdf" target="_blank">Check out here</a>

        </p>

-   <h2>Under Review</h2>

    -   <p>Liu, Y., Sorace, A., & Smith, K. (Under Review). Do bilinguals avoid ambiguity or minimise processing effort? Insights from an online eye-tracking study in spoken Mandarin. <a href="manuscript.pdf" target="_blank">Check out here</a></p>

<h1>Presentations</h1>

-   <h2>Selected Posters</h2>

    -   <p>Liu, Y., Sorace, A., & Smith, K. A desire to avoid ambiguity or ease processing? Insights from an experimental study of lexical ambiguity in spoken Mandarin using online eye-tracking. Poster to be presented at the 47th Annual Meeting of the Cognitive Science Society, San Francisco, US, August 2025. <a href="cogsci_poster.pdf" target="_blank">CogSci Poster</a></p>

    -   <p>Liu, Y., Sorace, A., & Smith, K. Mandarin bilingual speakers undergoing attrition produce more explicit referring expressions.(MORE DATA). Poster presented at the 30th Architectures and Mechanisms for Language Processing, University of Edinburgh, Edinburgh, UK, September 2024. <a href="AMLaP_poster.pdf" target="_blank">AMLaP Poster</a></p>

    -   <p>Liu, Y., Sorace, A, & Smith, K. Mandarin bilingual speakers undergoing attrition produce more explicit referring expressions.Poster presented at the 37th Human Sentence Processing, University of Michigan, Ann Arbor, US, May 2024. <a href="HSP_poster.pdf" target="_blank">HSP Poster</a></p>

    -   <p>Liu, Y., Luo, Q., Sorace, A, & Smith, K. Exploring the role of communicative interaction in L1 attrition: Evidence from null and overt subjects in an artificial language. Poster presented at Bilingualism Matters Research Symposium, Edinburgh, UK, October 2022. <a href="BMRS_poster.pdf" target="_blank">BMRS Poster</a></p>
